source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ASPlaceholderTextView_Example' do
  pod 'ASPlaceholderTextView'
end

target 'ASPlaceholderTextView_Tests' do
  pod 'ASPlaceholderTextView'

  
end
